### ISSUE TITLE
Single Template

### ISSUE THREAD

**Issue by mrpritchett** [LiftUX/velux-theme#4]

**Comment by imbradmiller** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;T9U5KjuJ&#x2F;23-velux-luxury-theme"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Velux (Luxury Theme)</a>
